---
title: "DC Data Cleaning Record"
author: "Max Anthenelli and Jiseung Yoo"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

working_directory <- file.path("C:", "Users", "Max", "Documents", "GitHub",
                             "DCPS")
# working_directory <- file.path("/Users/jiseungyoo/Desktop/DCPS/data")

box_directory <- file.path(working_directory, "..", "..", "..", 
                           "Box", "DCPS-SERP Data Internal 2019")

setwd(working_directory)

#getwd()
## choose required packages ----
c("tidyverse", "magrittr", "rlang", "glue",
  "haven", "labelled", "writexl",
  "gt", "gtsummary", "webshot2", 'readxl',
  "scales", "grid", "ggtext", "patchwork"
)  |>
  purrr::walk(~require(.x, character.only = TRUE))
```

Main Data Source comes from Excel sheet

```{r Clean Student Data}
excel_file <- file.path( box_directory, "Data", "Raw",  
                         "Student Data through SY22-23 Updated.xlsx") 
demog_student.year <-
  read_excel(excel_file, sheet = "Demographic")

enrollment_student.school.year <- 
  read_excel(excel_file, sheet = "Enrollment and Attendance")

courses_student.school.year <-   
  map(map_vec(c(19:22), ~glue("Courses SY{.x}-{.x+1}")),
      ~excel_file %>% read_excel(sheet = .x)) %>% 
  list_rbind()

tests_student.year <- 
  read_excel(excel_file, sheet = "PARCC")

assessments_student.year <-
  read_excel(excel_file, sheet = "Formative Assessments") %>% 
  filter(Assessment_Type %in% c("DIBELS", "RI", "TRC")) 

## Determine Primary Teacher ----
mode_stat <- function(x, na.rm = TRUE) {
  if(na.rm) x = x[!is.na(x)]
  ux <- unique(x)
  return(ux[which.max(tabulate(match(x, ux)))])
}

primary_teacher <- 
  courses_student.school.year %>% 
  group_by(StudentID, Grade, School, courses_sy_start) %>%
  mutate(Employee_Number = ifelse(any(Subject_Code == "EE"),
                                  mode_stat(Employee_Number[Subject_Code == "EE"]), Employee_Number)) %>%
  reframe(main_teacher = mode_stat(Employee_Number)) %>% 
  ungroup() %>% 
  mutate(Grade = ifelse(str_trim(Grade) == "K", "0", Grade) %>% parse_double()) %>% 
  rename(year = courses_sy_start, school_id = School)

## clean test scores ----
assessments_student.year %<>%
  mutate(etime = case_match(Assessment_Window,
                            "BOY" ~ "f", "MOY" ~ "m", "EOY" ~ "s", .default = NULL),
         tname = ifelse(Assessment_Type == "RI", "sri", Assessment_Type)) %>%
  rename(pb = Proficiency_Level, ss = Proficiency_Score) %>%
  select(-Assessment_Window, -Assessment_Type) %>% 
  pivot_wider(names_from = c(tname, etime), 
              values_from = c(pb, ss), names_glue = "s_{tname}_{.value}_{etime}") %>% 
  select(-contains("TRC_ss")) %>% 
  mutate(across(contains("_pb_"), ~case_match(.x, 
      c("Below Basic", "Well Below Benchmark", "Far Below Proficient") ~ 1, 
      c("Basic", "Below Benchmark", "Below Proficient") ~ 2, 
      c("Proficient", "Benchmark", "At Benchmark") ~ 3, 
      c("Advanced", "Above Benchmark", "Above Proficient") ~ 4, 
      .default = NULL)), 
      across(contains("_ss_"), ~parse_integer(.x)))

## merge and reformat ----
df <- enrollment_student.school.year %>% 
  group_by(StudentID, SchoolYearStart) %>% 
  filter(Membership_Days==max(Membership_Days)) %>% 
  reframe(Grade = min(ifelse(str_trim(Grade) == "K", "0", Grade) %>% parse_double(), na.rm = TRUE),
          school_id = min(School_ID, na.rm = TRUE), 
          s_days_enrolled = max(Membership_Days)) %>% 
  rename(year = SchoolYearStart) %>% 
  left_join(
    tests_student.year %>% rename(Grade = student_Grade),
    join_by(StudentID, Grade), relationship = "many-to-many") %>% 
  left_join(
    primary_teacher, join_by(StudentID, Grade, year, school_id), relationship = "many-to-many"
  ) %>% 
  left_join(demog_student.year %>% 
              mutate(Grade = ifelse(str_trim(Grade) == "K", "0", Grade) %>% parse_double()) %>%
              rename(year = School_Year_Start), join_by(StudentID, Grade, year)) %>% 
  left_join(assessments_student.year %>% 
              rename(year = School_Year_Start), join_by(StudentID, Grade, year)) %>%
  mutate(s_race = case_match(Race_Ethnicity,
                             "American Indian or Alaska Native" ~ 1,
                             "Asian" ~ 2,
                             "Black or African American" ~ 3,
                             "Hispanic/Latino" ~ 4,
                             "Two or More Races" ~ 5,
                             "White" ~ 6, .default = NULL),
         s_female = case_match(Gender, "F" ~ 1, "M" ~ 0, .default = NULL),
         s_sped = case_match(SPED, "Y" ~ 1, "N" ~ 0, .default = NULL),
         s_lep = case_match(EL_Indicator, "Yes" ~ 1, "No" ~ 0, .default = NULL),
         ela_test_grade = case_when(str_starts(ela_testcode, "ELA")
                                    ~ parse_number(str_remove(math_testcode, "ELA")), .default = NULL),
         math_test_grade = case_when(str_starts(ela_testcode, "MAT")
                                     ~ parse_number(str_remove(ela_testcode, "MAT")), .default = NULL),
         employeeid = parse_number(main_teacher)) %>% 
  rename(
    usi = StudentID,
    schoolyear_fall = year,
    s_grade = Grade,
    schoolid1 = school_id,
    s_parcc_pb_ela = ela_perf_level,
    s_parcc_ss_ela = ela_scale_score,
    s_parcc_pb_math = math_perf_level,
    s_parcc_ss_math = math_scale_score,
    birthdate = Birth_Date
  ) %>% 
  select(usi, schoolyear_fall, s_grade, schoolid1, ela_test_grade, 
         s_parcc_pb_ela, s_parcc_ss_ela, math_test_grade, s_parcc_pb_math,
         s_parcc_ss_math, employeeid, s_female, s_race,
         birthdate, s_lep, s_sped, s_days_enrolled, s_DIBELS_pb_s, 
         s_DIBELS_pb_f, s_DIBELS_pb_m, s_TRC_pb_s, s_TRC_pb_f, s_TRC_pb_m,
         s_sri_pb_s, s_sri_pb_m, s_sri_pb_f, s_DIBELS_ss_s, s_DIBELS_ss_f, 
         s_DIBELS_ss_m, s_sri_ss_s, s_sri_ss_m, s_sri_ss_f)

names(df) <- str_to_lower(names(df))

df_max <- df

df_js <- 
  courses_student.school.year %>% 
  group_by(StudentID, Grade, School, courses_sy_start) %>%
  filter(grepl("Elementary|language|english|reading|writing|literacy", Title, ignore.case = TRUE))%>%
  filter(!grepl("computer|spanish|native|latin|arabic|financial", Title, ignore.case = TRUE))  %>%
  reframe(lan_teacher = mode_stat(Employee_Number)) %>% 
  ungroup() %>% 
  mutate(Grade = ifelse(str_trim(Grade) == "K", "0", Grade) %>% parse_double()) %>% 
  rename(
    schoolyear_fall = courses_sy_start,
    schoolid1 = School,
    usi = StudentID,
    s_grade = Grade,
    language_teacher= lan_teacher) %>% 
  right_join(
    df_max, join_by(usi, s_grade, schoolyear_fall, schoolid1)) %>%
  group_by(schoolyear_fall, s_grade) %>%
  mutate(across(
    c(s_dibels_ss_s, s_dibels_ss_f, s_dibels_ss_m,
      s_sri_ss_s, s_sri_ss_m, s_sri_ss_f),
    ~ scale(., center = TRUE, scale = TRUE),
    .names = "{.col}_sd"
  )) %>%
  ungroup() %>%
  rename(
    s_dibels_ss_sd_s= s_dibels_ss_s_sd, 
    s_dibels_ss_sd_f= s_dibels_ss_f_sd, 
    s_dibels_ss_sd_m= s_dibels_ss_m_sd, 
    s_sri_ss_sd_s= s_sri_ss_s_sd, 
    s_sri_ss_sd_m= s_sri_ss_m_sd, 
    s_sri_ss_sd_f= s_sri_ss_f_sd,
    teacherid = employeeid,
    employeeid = language_teacher
    ) %>% ### switch teacher main - language
  mutate(
      s_white = as.integer(s_race == "6"),
      s_black = as.integer(s_race == "3"),
      s_native_american = as.integer(s_race == "1"),
      s_asian = as.integer(s_race == "2"),
      s_latinx = as.integer(s_race == "4"),
      s_race_multi_other = as.integer(s_race == "5"),
      employeeid = as.numeric(employeeid))
  

# df_js_sd %>%
#   filter(s_grade %in% c(0:8)) %>% 
#   write_dta( file.path(working_directory, "student_level_js.dta"))

```


```{r add observation scores}
observation_data <-
  file.path( box_directory, "Data", "Raw", "SERP Classroom Observations",
             "DCPS_Observation Data_charts_0124.xlsx") %>%  
  read_excel() %>% t() %>% as_tibble()

names(observation_data) <- observation_data[3,] %>% as_vector() %>%
  str_replace_all(" ", "_")

names(observation_data)[is.na(names(observation_data))] <- "unknown"

observation_data[-c(1:3),] %>% 
  rename(employeeid = DCPS_Teacher_ID) %>%
  filter(!is.na(employeeid)) %>% 
  mutate(schoolyear_fall = 2021, employeeid = parse_double(employeeid)) %>% 
  arrange(employeeid, schoolyear_fall) %>% 
  left_join(df_js, by = c("employeeid", "schoolyear_fall"))
```


```{r declare relevant vectors}
english_course_titles <- c(glue("English {6:8}"), glue("Advanced English {6:8}"), 
  glue("Pre-AP English {6:8}"), glue("English FT {6:8}"),
  glue("English & Humanities {6:8}"),
  "English I", "Language, Culture and Literacy", glue("Language Arts {6:8}"),
  "English as a Second Language I", "English as a Second Language II",
  "IB MYP English II") # does Journalism count??

supplemental_english_titles <- c(
  glue("Reading Resource MS{6:8}"),
  glue("Reading Workshop {c(6:8, 'MS')}"),
  "Reading Support MS",
  "Newc Engl Lit Devt MS", "Newc Oral LangDevt MS",
  "Beginning ESL MS", "Intermed ESL MS", "Advanced ESL MS",
  "Extended Literacy MS",
  "Reading Lab", "LL: Miixed-Model Reading MS7",
  glue("LL: Mixed-Model Reading MS{6:8}"),
  glue("AVID Grade {6:8}") # this isn't specifically literacy but I found their website
)

unrelated_subject_codes <- 
  c("ADM", "ART", "CARR", "CTE", "EE", "FL", "MAT", "MU", "NULL", NULL, "PE",
    "SCI", "SS", "WL")

stari_schools <- c(347, 404, 454, 405, 407, 413, 1071, 435, 416, 428)
# 347 Brookland
# 404 Browne
# 454 Cardozo
# 405 Deal
# 407 Eliot
# 413 Hart
# 1071 Ida B (Wells)
# 435 Mckinley
# 416 Johnson
# 428 Stuart-Hobson
```



```{r merge stari}
STARI <- 
  file.path(box_directory, "Data", "Raw", "STARI") %>% 
  list.files(pattern = "\\.xlsx$", full.names = TRUE) %>% 
  map(~{read_excel(.x) %>% as_tibble()})

schools_teacher_list <- STARI[[2]] %>% filter(Grade!="9th-12th") %$% unique(School)


sheets <- file.path(box_directory, "Data", "Raw", "STARI") %>% 
  list.files(pattern = "\\.xlsx$", full.names = TRUE) %>% 
  .[1] %>% 
  excel_sheets()

map()

STARI[[1]] %>% view()

STARI[[2]] %>% filter(Grade!="9th-12th") 
# it looks like there is Wells MS in teacher and "Ida B Wells MSS" in combined

schools_combined_sheets <- map(3:8,~STARI[[.x]] %$% unique(SCHOOL_NAME)) %>% list_c() %>% unique() 

setdiff(schools_teacher_list, schools_combined_sheets) %>% 
c(
  setdiff(schools_combined_sheets, schools_teacher_list)
)

binder <- 
  file.path(box_directory, "Data", "Raw", "STARI", "binder_info.xlsx") %>% 
  read_excel() %>% 
  mutate()

binder$Teacher

school_cross_walk <- file.path(box_directory, "Data", "Raw", "School Names IDS.xlsx") %>% 
  read_excel() 

clean_names <- function(data) {
  data %>% 
    pull(Teacher) %>% 
    str_to_lower() %>% 
    str_replace_all("['_]", "") %>% 
    unique() %>% 
    unlist()
}

stari_teacher <- clean_names(binder) %>% 
c(clean_names(STARI[[2]] %>% filter(Grade!="9th-12th"))) %>% 
  unique()
binder %>% view()

school_cross_walk %>% filter()

courses_student.school.year %>% 
    pull(Teacher) %>% 
    str_to_lower() %>% 
    str_replace_all("['_,]", "") %>% 
    unlist()
    

teachers <- stari_schools %>% 
  map(~{
    courses_student.school.year %>% 
      filter(School==.x, courses_sy_start==2022,
             Title %in% supplemental_english_titles) %>% 
      select(School, Title, Section, Teacher, Grade, Employee_Number) %>% 
      group_by(School, Teacher, Grade) %>% 
      reframe(School = first(School), 
              Title = first(Title), 
              Section = first(Section), 
              Teacher = first(Teacher), 
              Grade = first(Grade),
              Employee_Number = first(Employee_Number))
  }) %>%
  list_rbind() %>% 
  select(Teacher, Employee_Number)

teachers %>% 
  mutate(
    name1 = Teacher %>% str_replace_all("-", " ") %>% str_replace_all(",", "") %>% word(1),
    name2 = Teacher %>% str_replace_all("-", " ") %>% str_replace_all(",", "") %>% word(2),
    name3 = Teacher %>% str_replace_all("-", " ") %>% str_replace_all(",", "") %>% word(3),
    name4 = Teacher %>% str_replace_all("-", " ") %>% str_replace_all(",", "") %>% word(4),
    name5 = Teacher %>% str_replace_all("-", " ") %>% str_replace_all(",", "") %>% word(5)
  ) %>% 
  pmap_df(function(...) {
    sort(c(...), na.last = TRUE)
  }) %>% 


library(tidyverse)

teachers %>% 
  mutate(
    names = str_replace_all(Teacher, "-", " ") %>% 
            str_replace_all(",", "") %>% 
            str_split(" ") %>% 
            map(~sort(.x))
  ) %>%
  mutate(
    name1 = word(names, 1),
    name2 = word(names, 2),
    name3 = word(names, 3),
    name4 = word(names, 4),
    name5 = word(names, 5)
  )
  
teachers %>% 
  mutate(
    names = str_replace_all(Teacher, "-", " ") %>% 
            str_replace_all(",", "") %>% 
    str_split(" ") %>% 
    map(sort) %>%
    unlist()) %>% 
  mutate(
    name1 = word(names, 1),
    name2 = word(names, 2),
    name3 = word(names, 3),
    name4 = word(names, 4),
    name5 = word(names, 5)
  )
  
%>% 
  str_split(" ")

%>% 
  str_replace_all("[ ,\\/]", "")

clean_names <- function(data, col_name) {
  data %>% 
    mutate(name1 = str_extract())
}

courses_student.school.year %>% names()
courses_student.school.year %>%
  mutate(Teacher = clean_names(., "Teacher"))
  filter(Title %in% supplemental_english_titles,
         Teacher)

tab_schools_combined <- map(3:8, ~STARI[[.x]] %>% count(SCHOOL_NAME)) %>% list_rbind()
tab_schools_combined %>% view()

tab_schools_combined %>% 
  reframe(total = sum(n)) %>% 
  view()

sc
# so I guess the question here is 
#This data is from 22-23 school year  
  
studentdf <- df_js %>% 
  filter(s_grade %in% 6:8) %>%
  group_by(usi, s_grade, schoolid1, schoolyear_fall) %>%
  mutate(engscore = (s_dibels_ss_sd_f + s_sri_ss_sd_f) / 2) %>%
  ungroup()

results <- 
  map(supplemental_english_titles, 
    ~ {courses_student.school.year %>%
        group_by(Grade, School, courses_sy_start) %>%
        reframe(percentage_students = 
          n_distinct(StudentID[Title == .x]) / n_distinct(StudentID)*100) %>% 
        filter(percentage_students!=0) %>% 
        mutate(Title = .x)
    }) %>% 
  list_rbind() %>% 
  pivot_wider(names_from = Title, values_from = percentage_students) %>% 
  as_tibble()

results %>% 
  filter(School %in% stari_schools) %>% 
  view()


```

